 ## Creating a logistic regression to predict absenteeism

## import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

### here I will find median of absenteeism_time in order to classify people

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

### In this case hours >=4 excessively absent, hours<=3 moderately absent. So for excessive we'll assign 1, and for moderate 0. In supervised learning these 0s and 1s :TARGETS

In [4]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>
                 data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism']=targets
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 16 columns]

#####  Target should be balanced, there should not be big gap between the number of excessive absence and moderate. Here this proportion is 45:55, which is sufficient to work on. 

In [7]:
targets.shape[0]

700

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week',
                                          'Daily Work Load Average', 'Distance to Work'], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

##### Select the inputs for the regression; entire data frame will be taken as inputs, except "Excessive absenteesm"

In [10]:
unscaled_input=data_with_targets.iloc[:, :-1]
unscaled_input.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                     289   33               30          0         2     1  
1                     118   50               31          0         1     0  
2                     179   38               31          0         0     0  
3                     279   39               24          0         2     0  
4                     289   33               30          0         2     1

### Standardize the data

In [11]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler=StandardScaler()

####  The entire input will be standarzed except dummy values. Since dummy values are already binary and they are not quantitive variables, scaling them could cause losing interprete ability of the dummies.  So reasons and education columns  will be out of scope of scaling. For this reason CustomScaler which is based on StandardScaler will be used.

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
    
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [13]:
unscaled_input.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

### now, we will create a new variable for scale called columns to Scale that will contain the columns we'd like to scale 

### ----Backward elimination comment----      While doing backward elimination we should remove the same column names from columns_to_scale, but to have more dynamic code, and this case we dont need to delete the column name manually for every change of df.

In [14]:
#columns_to_scale=['Month Value','Day of the Week','Transportation Expense','Distance to Work','Age','Daily Work Load Average','Body Mass Index','Children','Pets']
columns_to_omit= ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [15]:
#columns_to_scale

In [16]:
columns_to_scale=[x for x in unscaled_input.columns.values if x not in columns_to_omit ]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [17]:
absenteeism_scaler=CustomScaler(columns_to_scale)
absenteeism_scaler

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

##### we have created an empty custom scaler object. absenteeism scaler will be used to subtract the mean and divide by the standard deviation from each point of variablewise

In [18]:
absenteeism_scaler.fit(unscaled_input)

C:\Users\igsum\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

### the result of above line will be stored in the absenteeism_scaler object, so it wont be empty anymore

In [19]:
scaled_inputs=absenteeism_scaler.transform(unscaled_input)

In [20]:
scaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1     0.182726   
1         0         0         0         0     0.182726   
2         0         0         0         1     0.182726   
3         1         0         0         0     0.182726   
4         0         0         0         1     0.182726   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

## Split the data into train and test and shuffle

### Import the relevant module

In [21]:
from sklearn.model_selection import train_test_split

### Split

In [22]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 475         0         0         0         1     0.182726   
 334         1         0         0         0     1.324766   
 673         0         0         0         1    -0.673803   
 697         1         0         0         0    -0.388293   
 44          0         0         0         1     0.753746   
 ..        ...       ...       ...       ...          ...   
 607         0         0         0         1    -1.244823   
 582         1         0         0         0    -1.530333   
 487         0         0         0         1     0.468236   
 484         0         0         0         1     0.468236   
 96          1         0         0         0     1.324766   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 475                1.005844 -0.536062         0.767431          0  0.880469   
 334                0.568211 -0.065439        -0.878984          0  2.679969   
 673               -0.6541

In [23]:
x_train, x_test, y_train, y_test=train_test_split(scaled_inputs, targets, train_size=0.8)

In [24]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [25]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


### Logistic regression with sklearn
### StatsModels is not compatible with the more complicated models, therefore scikit-learn ML librarie used for Logistic Regression

In [26]:
from  sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [27]:
reg=LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

In [28]:
reg.score(x_train, y_train)

0.7767857142857143

### Checking the accuracy manually

In [29]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,

In [30]:
model_outputs==y_train

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,

In [31]:
np.sum((model_outputs==y_train))

435

In [32]:
model_outputs.shape[0]

560

In [33]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7767857142857143

### Finding the intercept and coefficients

In [34]:
reg.intercept_

array([-1.82325675])

In [35]:
reg.coef_

array([[ 2.95999581,  0.7580335 ,  2.99760918,  0.85835886,  0.09242242,
         0.63019927, -0.1480748 ,  0.18818646,  0.34939167,  0.35960526,
        -0.31403489]])

### we are going to create new table with feature name, and then add coef column to it

In [36]:
feature_name=unscaled_input.columns.values
feature_name

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [37]:
summary_table=pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table

Feature name
0                 Reason_1
1                 Reason_2
2                 Reason_3
3                 Reason_4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                    Pets

In [38]:
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.959996
1                 Reason_2     0.758033
2                 Reason_3     2.997609
3                 Reason_4     0.858359
4              Month Value     0.092422
5   Transportation Expense     0.630199
6                      Age    -0.148075
7          Body Mass Index     0.188186
8                Education     0.349392
9                 Children     0.359605
10                    Pets    -0.314035

### The code below is to have empty index in order to add "Intercept" on the top the data frame.

In [39]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept', reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.823257
1                 Reason_1     2.959996
2                 Reason_2     0.758033
3                 Reason_3     2.997609
4                 Reason_4     0.858359
5              Month Value     0.092422
6   Transportation Expense     0.630199
7                      Age    -0.148075
8          Body Mass Index     0.188186
9                Education     0.349392
10                Children     0.359605
11                    Pets    -0.314035

### Adding exponential values of coef as "odds ratio"

In [40]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.823257    0.161499
1                 Reason_1     2.959996   19.297891
2                 Reason_2     0.758033    2.134075
3                 Reason_3     2.997609   20.037573
4                 Reason_4     0.858359    2.359286
5              Month Value     0.092422    1.096828
6   Transportation Expense     0.630199    1.877985
7                      Age    -0.148075    0.862367
8          Body Mass Index     0.188186    1.207059
9                Education     0.349392    1.418205
10                Children     0.359605    1.432764
11                    Pets    -0.314035    0.730494

#### sorting out dataframe by 'odds_ratio' column, by default it will sort ascending, so by adding extra parameter we will sort it by descending 

In [41]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     2.997609   20.037573
1                 Reason_1     2.959996   19.297891
4                 Reason_4     0.858359    2.359286
2                 Reason_2     0.758033    2.134075
6   Transportation Expense     0.630199    1.877985
10                Children     0.359605    1.432764
9                Education     0.349392    1.418205
8          Body Mass Index     0.188186    1.207059
5              Month Value     0.092422    1.096828
7                      Age    -0.148075    0.862367
11                    Pets    -0.314035    0.730494
0                Intercept    -1.823257    0.161499

#### Let's interpret this new dataframe. If variable's coef is around 0 and odds ration is around 1 it means that the corresponding feature is not so important.
#### A coef(weight) of 0 implies that no matter the feature value, we'll multiply it by 0 (in the model)
#### For a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio (1=no change)

#### since "day of the week", "Daily Work Load Average", "Distance to Work" almost dont have impact to our model (as we see from coef and oods_ratio) we can eliminate these features from df. This is also called backward elimination. So we are going back to add these feature to drop list.  And after dropping those feature the accurecy model has not changed, since they didnt have impact on the model. Moreover, the simplest model (which contains less amount of features) is always better.

#### So, in order to simplify data frame I am going back to the checkpoint (where 'Absenteeism Time in Hours' column dropped and new df named "data_with_targets") to drop 'Day of the week', 'Daily Work Load Average', 'Distance to Work'.

## Now its time to test our model
#### Once we test our model we should not touch the model to improve our model. Because if we are doing that this won't be testing anymore, it means we are training our model a bit more. In conclusion test data should not be part of training process.

In [42]:
reg.score(x_test,y_test)

0.7071428571428572

#### So based on data that the model has never seen before, we can say that in 75% of the cases the model will predict if a person is going to be excessively absent. As we see the accuracy is not same as on the training data, it's less than as always.


In [43]:
predicted_probability=reg.predict_proba(x_test)
predicted_probability                         

array([[0.32703898, 0.67296102],
       [0.62716716, 0.37283284],
       [0.42611559, 0.57388441],
       [0.68849146, 0.31150854],
       [0.81140898, 0.18859102],
       [0.30718327, 0.69281673],
       [0.68511137, 0.31488863],
       [0.29271497, 0.70728503],
       [0.81140898, 0.18859102],
       [0.7926693 , 0.2073307 ],
       [0.80717969, 0.19282031],
       [0.59260612, 0.40739388],
       [0.28190952, 0.71809048],
       [0.07551508, 0.92448492],
       [0.10689067, 0.89310933],
       [0.78829915, 0.21170085],
       [0.44051668, 0.55948332],
       [0.81541377, 0.18458623],
       [0.81541377, 0.18458623],
       [0.50240502, 0.49759498],
       [0.32125821, 0.67874179],
       [0.46667067, 0.53332933],
       [0.74790406, 0.25209594],
       [0.79472431, 0.20527569],
       [0.6209766 , 0.3790234 ],
       [0.57980536, 0.42019464],
       [0.08039682, 0.91960318],
       [0.76750923, 0.23249077],
       [0.31792939, 0.68207061],
       [0.16323819, 0.83676181],
       [0.

### Save the model

In [44]:
import pickle

In [45]:
 with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [46]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)